core:
  debug_mode: false
  log_level: INFO
  enabled_components:
    - voice
    - vision
    - hearing
    - automation

voice:
  enabled: true
  api_url: http://localhost:8100
  volume: 0.8
  speed: 1.0
  pitch: 1.0
  emotion: normal

vision:
  enabled: true
  capture_method: auto
  use_ocr: true

hearing:
  enabled: true
  wake_word: hey sabrina
  silence_threshold: 0.03

automation:
  enabled: true
  mouse_move_duration: 0.2
  typing_interval: 0.1