version: '3.8'

services:
  voice-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sabrina-voice-api
    ports:
      - "8100:8100"
    restart: unless-stopped
    # Audio configuration based on platform
    # Option 1: Use this on Linux if you need direct sound access
    # devices:
    #   - /dev/snd:/dev/snd
    # Option 2: For PulseAudio on Linux
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      # Uncomment the line below for PulseAudio (Linux only)
      # - ${XDG_RUNTIME_DIR}/pulse:/run/pulse:ro
    environment:
      - TZ=UTC
      # Uncomment the line below for PulseAudio (Linux only)
      # - PULSE_SERVER=unix:/run/pulse/native