services:
  voice-api:
    build:
      context: .
      dockerfile: voice.Dockerfile
    container_name: sabrina-voice-api
    ports:
      - "8100:8100"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models  # Add models volume
    environment:
      - VOICE_API_PORT=8100
      - VOICE_API_KEY=${VOICE_API_KEY:-sabrina-dev-key}
      - DEBUG=${DEBUG:-false}
    restart: unless-stopped
