version: '3.8'

services:
  voice-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sabrina-voice-api
    ports:
      - "8100:8100"
    volumes:
      - ./models/piper:/app/models
      - ./config:/app/config
      - ./data/tts_cache:/app/data/tts_cache
      - ./logs:/app/logs
    environment:
      - TTS_MODEL_DIR=/app/models
      - TTS_CACHE_DIR=/app/data/tts_cache
    restart: unless-stopped
    networks:
      - sabrina-network

networks:
  sabrina-network:
    driver: bridge
