version: '3.8'

services:
  voice-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sabrina-voice-api
    ports:
      - "8100:8100"
    restart: unless-stopped
    volumes:
      - ./models/piper:/app/models/piper
      - ./logs:/app/logs
      # For Linux systems with PulseAudio
      # - ${XDG_RUNTIME_DIR}/pulse:/run/pulse:ro
    environment:
      - TZ=UTC
      # For Linux systems with PulseAudio
      # - PULSE_SERVER=unix:/run/pulse/native