version: "3.8"

services:
  hearing:
    build:
      context: ../..  # Moves the build context to the root directory
      dockerfile: docker/hearing/hearing.Dockerfile
    container_name: hearing-container
    ports:
      - "8000:8000"  # Expose API
